### ISSUE TITLE
Always printing the used seed

### ISSUE THREAD

**Issue by AndreaCrotti** [lambdaisland/kaocha#106]
I know that the seed number is mostly to reproduce a failure, but sadly in case of crappy tests that fail if run in a certain order, I ended up using it also to make sure tests always pass.

The problem is that the seed is only printed out when there is a test failure, not when they actually work, so it's a bit hard to grab it.
Would it be possible to just print out the seed in any case?

**Comment by plexus** [comment]
We used to always print it, but changed that to be less noisy, so I don't want to go back on that, but I'm ok with having it be configurable in `tests.edn`. Happy to provide feedback on a PR!

``` clojure
#kaocha/v1
{:kaocha.plugin.randomize/print-seed? :always ;; :never :on-failure
 }
```

Alternatively why not just turn of randomization and have your tests run in load order?

Keep in mind this is an extreme case, since what you're really saying is that your test suite is broken, but you don't want to know.

**Comment by plexus** [comment]
If you don't need it right now then I would leave it as is. If someone else find this issue and thinks they need it then maybe they can have a go at it. Another workaround could be to just try some seed numbers until one works :)

**Comment by AndreaCrotti** [comment]
Well for tests that take a very long time to run it's not very suitable.
What I was trying was to simply print the test plan, and see in what order tests are listed there.
I noticed though btw that the test plan always contain all the tests, even if I was running it with `--focus-meta :integration-test`, is that a bug or it's expected?

**Comment by plexus** [comment]
That's expected, you'll find that the other tests all have a `:skip` flag on them.

**Comment by AndreaCrotti** [comment]
Cool ok I can close this, thanks

**Comment by countgizmo** [comment]
@plexus I have an argument, an actual use case, for having the configuration option to enable seed printing before each test run.

Our test suite (kaocha-clj) runs in CI. The randomised feature is enabled by default and we love it - it helped us find some weird test dependencies (aka incorrect tests). Not often but every now an then we'll get a failed test in CI that does not fail on local (tests in CI run a lot more often than locally, so there's higher probability to find a test dependency).For debugging purposes we usually try to reproduce the same test run in the same context but without having the seed available in the CI logs there's no way to be sure you're truly rerunning the same test sequence.

I would personally have the option to print seeds always _on_ because in the context of a random test suite execution developers should have a way to reproduce a specific run. And kaocha already has ways to le users specify the seed, however this feature seems to be missing an important counterpart at the moment :)

Please let me know if you would prefer a separate issue to track this.

And as always: thank you for the awesome work!

**Comment by plexus** [comment]
I'm not sure I understand. If the tests fail then the seed will be visible in the CI log, no?

In any case the seed is part of the test plan, you can print it out in a hook if you need it at a specific point in time.

**Comment by countgizmo** [comment]
As I recall the tests didn't just fail - they crashed because of an uncaught exception, so kaocha couldn't printout the failed tests and the caught output :)

Thanks for the hook suggestion - I'll write it down and try to figure it out.

**Comment by plexus** [comment]
I see, that makes sense. Although unless it's something non-recoverable like an out of memory exception kaocha should still catch it and report it, and then print the seed at the end. If it doesn't then that's a bug and you can create an issue for that. Thanks!

**Comment by plexus** [comment]
Example of a hook:

``` clojure
#kaocha/v1
{:plugins [:kaocha.plugin/hooks]
 :kaocha.hooks/pre-run [(fn [test-plan]
                          (println "Seed:" (:kaocha.plugin.randomize/seed test-plan))
                          test-plan)]}
```

**Comment by countgizmo** [comment]
@plexus This worked beautifully! Thank you!
