### ISSUE TITLE
Unhelpful error message when ns-patterns is a string

### ISSUE THREAD

**Issue by miikka** [lambdaisland/kaocha#124]
I had the following config where `:ns-patterns` is a string, not a vector as expected:

```clojure
#kaocha/v1
{:test-paths ["test"]
 :tests [{:id :unit, :ns-patterns "test"]}]}
```

I got the following error message with Kaocha 0.0-554:

```
Execution error (ClassCastException) at kaocha.config/replace-by-default (config.clj:21).
java.lang.String cannot be cast to clojure.lang.IObj

Full report at:
/var/folders/8s/w7wls65s2vvdml8ztk54jfch0000gn/T/clojure-2320317278819008693.edn
```

Took me a while to figure out what is going on – a better error message would help here.

**Comment by plexus** [comment]
We have specs for these things, but I guess they're not being checked at the right time.

**Comment by plexus** [comment]
This seems to happen because we try to put some metadata on this value before passing it to meta-merge, and you can't put metadata on a string.

``` clojure
;; kaocha.config

(defn replace-by-default [config k]
  (if-let [v (get config k)]
    (if (#{:prepend :append} (meta v))
      config
      (update config k vary-meta assoc :replace true)) ;; <---------------- here
    config))
```

@robhanlon22 has a work in progress to add more spec validation (#165), but it seems that one still shows the same error. It probably could be fixed there by making the specs more detailed (`(s/keys ... coll?)` instead of just `map?`). But I think we can also just add an explicit check here, that way we can finely control the error message.

``` clojure
(if (coll? v)
  (update config k ...) ;; as before
  (do
    (output/error "Test suite configuration key " k " should be a collection, but got " v)
    (throw+ {:kaocha/early-exit ... }))) ;; we need to pick a unique number here
```
