### ISSUE TITLE
Preload not working with cljs

### ISSUE THREAD

**Issue by ikitommi** [lambdaisland/kaocha#152]
It seems that the `:preload` plugin doesn't load code with cljs. My `tests.edn` looks like:

```clj
#kaocha/v1
{:tests [{:id   :unit
          :type :kaocha.type/clojure.test}
         {:id   :unit-cljs
          :plugins [:preloads]
          :kaocha.plugin.preloads/ns-names [sci.core]
          :type :kaocha.type/cljs}]}
```

fails, using cljs-test-runner with:

```clj
{:optimizations :none, :preloads [sci.core]}
```

works.

**Comment by alysbrooks** [comment]
Closing this because we suggest using the preloads key in the ClojureScript configuration instead. Note that while we would accept a PR for this, we would have a fairly high bar for it since our recommended solution is the preloads key. I'm saying this mostly because manipulating the ClojureScript compiler from Kaocha strikes me as likely to be hacky. Maybe there's a robust solution I missed.
