### ISSUE TITLE
Mismatched namespaces silently ignore tests

### ISSUE THREAD

**Issue by wavejumper** [lambdaisland/kaocha#153]
We have observed that kaocha silently ignores tests when there is a mismatch between the `ns` declaration and the file on the classpath. 

Eg: `example_test.clj` with `(ns example_test)` will silently ignore all tests in this namespace. 

Obviously, `example_test` is incorrect, but it's an easy mistake to make -- especially as I have observed Cursive incorrectly refactoring/creating namespaces with an underscore.

`lein test` does not silently drop tests in this particular case.

My expectation would be that kaocha either behaves like `lein test` or that it throws a classpath exception.

I have created a repo that demonstrates the issue here: https://github.com/wavejumper/kaocha-mismatched-namespaces

**Comment by plexus** [comment]
The issue here is that the namespace name does match the configured `:ns-patterns`, if I add a tests.edn to your repo like this:

``` clojure
#kaocha/v1
{:tests [{:ns-patterns [".*"]}]}
```

then it runs the test fine. Kaocha by default only runs namespaces that end in `-test`, which in this case is not the case.

For considerations regarding that default see #183 and #34 .
