### ISSUE TITLE
Make `--print-test-plan` readable (was: Simpler test plan?)

### ISSUE THREAD

**Issue by AndreaCrotti** [lambdaisland/kaocha#173]
`--print-test-plan` is a great feature, however the map is very nested and has lots of information, so it's actually quite hard to consume.

I think what (for me at least) is quite interesting to see is actually just the list of tests that will actually be run, in a form like

- ns.file/test-foo
- ns.file2/test-bar

it can be done by analysing the test plan, but I was wondering if it could be a feature that others might like to have?

**Comment by plexus** [comment]
`--print-test-plan` was always meant for consumption by other tools, not for human consumption, but I agree it is of limited use right now, because what is printed is not actually readable. There are a bunch of atoms and `java.io.File` and such in there. I've long thought we should clean that up, so that you could pipe the result into babashka for instance. Then we could easily put some one-liners in the documentation to give some ideas of what to do with that.

To your specific question we do already have `--print-test-ids` from the `kaocha.plugin.alpha.info` plugin. This does print all test ids, not just the ones that will run, but I'd welcome a PR to add an extra option for that. Maybe `--print-test-plan-ids`.

**Comment by AndreaCrotti** [comment]
Mm I just tried to run print-test-ids and it prints different lists depending on what test id I pass, so it's not really printing every possible thing, but uses the test plan already,  so maybe this is already doing the thing I was looking for?

**Comment by plexus** [comment]
Hah, I guess the underlying api for iterating the test plan already deals with skipped tests, so yeah maybe this is all you need.
