### ISSUE TITLE
How to setup environment variables for testing?

### ISSUE THREAD

**Issue by mhd53** [lambdaisland/kaocha#204]
Hi,

I have recently been trying to integrate `kaocha` into my test workflow - however it seems that there is no documentation that mentions how to set env vars dynamically when I run tests using `kaocha`. The concept of `profiles` is also a bit foreign and unclear when it comes to the docs.

Currently I have a `project.clj` file that has 3 different profiles one of them being `test`. In this profile I simply import another `test-config.edn` file which contains env vars such as a `database-url` that is different from the `dev` db url. 

Would it be possible if you can clarify for me how I can integrate such an env var when using `kaocha` as my test runner?

It would also be useful for others if such an example is incorporated explicitly within the docs since this is such a common use case when it comes to testing software.

Thank you,

Moe

**Comment by plexus** [comment]
Hi @mhd53 ,

Env vars are not Kaocha's responsibility, since you can't set env vars from within the process that is reading them.

You can `export` them in your `bin/kaocha`. If you're using a wrapper library like environ then you can look at what affordances it has for overriding environment variable values.

Profiles are a [Aero](https://github.com/juxt/aero) feature, maybe reading those docs will help clarify things. We merely provide the profile to Aero when reading `tests.edn`, what you do with that is up to you. The profile is `:ci` if `(= (System/getenv "CI") "true")`, otherwise it's `:default`, or whatever you set it to with `--profile`.

**Comment by mhd53** [comment]
Hi @plexus,

Thank you for your reply. I will close this issue now since I am no longer concerned with getting env vars to work with `kaocha`.
