### ISSUE TITLE
Kaocha-midje plugin and reporters

### ISSUE THREAD

**Issue by f1wade2** [lambdaisland/kaocha#230]
The dots reporter doesn't seem to work when used with Kaocha.midje plugin.

There doesn't seem to be much additional documentation around it, so I haven't been able to find out much more about using that plugin, as it also seems to change the clojure.spec output message.

Is there anything specific we need to add/edit to test using midje, to get the same output as you do in clojure.test?

Or how we change the spec output back to Spec's own output?

**Comment by plexus** [comment]
Hi @f1wade2, the midje test type is experimental at best, and we're not planning to put any more work into it. Midje is a weird beast and is mostly considered legacy. If you like the syntax of Midje but aren't too tied to Midje itself then we recommend moving to Fudje, which should have excellent Kaocha support since it's just clojure.test under the hood.
