### ISSUE TITLE
Optional filter on buffer data before write

### ISSUE THREAD

**Issue by sirmspencer** [lambdaisland/kaocha#405]
It would be great if we could filter the output instead of dumping it all.  For example, each of our tests reconnects to postgres with a fixture.  This logs some debug data that isn't relevant to the test itself.  With many tests, it makes sorting through that output to find the actual errors is extra work.

I am not sure if would go with the buffer:
https://github.com/lambdaisland/kaocha/blob/v0.0-118/src/kaocha/plugin/capture_output.clj

Or with the reporter
https://github.com/lambdaisland/kaocha/blob/v0.0-118/src/kaocha/report.clj#L126

**Comment by alysbrooks** [comment]
Hi @sirmspencer! That could definitely be very useful. I think what we want to add that feature to capture_output, perhaps by doing something similar to the bypass macro (https://github.com/lambdaisland/kaocha/blob/f071c105184a388ec7f26e33e1832b8d75167074/src/kaocha/plugin/capture_output.cljc#L110). 

I also wonder if it could be hooked into a logging library like log4j to filter entries in a more structured way. 

Another thing to consider is that you may want to change the logging at the source when you're running tests, e.g., change the log level to a higher one or disable logging from certain namespaces. I suspect filtering from Kaocha would be most useful for noisy libraries or when debugging a failing test. There might be other cases where the kind of filtering you want to do is very test-specific, and you don't want to change how you do production logging for the sake of tests. I don't know if you have any thoughts on that based on your experience.

Finally, is this something you would want to attempt a PR for? (I'm not sure whether you're asking about the buffer and reporter just to document some implementation options or because you want to take a crack at it.)

**Comment by sirmspencer** [comment]
I have not worked with buffers very often, so I don't know where to begin for that.  If you said in the reporter, its a pretty simple string operation to split, apply a pred, and rejoin.

It would be nice if I could programmatically turn off certain logging, but that's also something I have never seen.

**Comment by sirmspencer** [comment]
> Note that you can certainly create a reporter in your own namespace

Good point!  Its funny, I do this by default for react packages (most are bloated), but forget to do so in clojure.  I think this solves it for me, if no one else wants to take on the buffer filtering.
