### ISSUE TITLE
Print captured output for successful tests

### ISSUE THREAD

**Issue by cjohansen** [lambdaisland/kaocha#50]
Kaocha currently captures output and only prints it when tests fail. I like the idea behind this, but the current implementation makes it a little too easy to forget stray `prn`s around tests and implementation code. To me it would be ideal if:

- Output is captured, but always printed, grouped by name of test
- When there are both successful and failing tests, output from successful tests are printed before failing ones
- A command line argument can be used to configure printing for the whole test run: never, only failing, always
- Metadata can be used to configure printing per namespace/test: never, only failing, always

**Comment by plexus** [comment]
These are some interesting ideas... my first reaction was that the default of capturing and hiding output is quite deliberate, but maybe you're right and we shouldn't hide it by default, but make it configurable. There's already been cases where people think some aspect of Kaocha isn't working because they can't see their `println`s, so we're violating the principle of least surprise.

I'd be happy to review and merge a PR for each of the points you list.

Alternatively you or someone else could also publish their own version of the `capture-output` plugin (e.g. `my.org/kaocha-better-capture`), where they can live out whatever ideas for improvement they have. The whole idea with Kaocha's plugin system is to encourage this kind of marketplace of ideas. People who want can use it straight away, and we can take our time to consider which bits make sense to migrate to Kaocha itself.

**Comment by cjohansen** [comment]
Cool! I wasn't aware that I could control this with a plugin. I really do think this would be an improvement of the default experience but treading water in plugin sounds like a good idea. I'll put it on my ever-growing list of stuff to do :) 👍

**Comment by danielcompton** [comment]
FWIW, I really like that printing is only shown in failing test cases, though I can see how people could get confused by that. Another idea would be to print a line saying "152 lines of output hidden" at the end of the test run, or something similar, although that's also a little bit noisy.

**Comment by frozar** [comment]
The default hiding of print is surprising I must say. I understand the purpose of it however.

My not familiar at all with the kaocha software as itself and even less with its ecosystem.
Does it exist a plugin to reveal user print?

If not, is there a workaround to able user print? Something like `binding` block for example.

**Comment by plexus** [comment]
You can disable the output capturing in tests.edn or from the command line with --no-capture-output

**Comment by frozar** [comment]
Nice, thank you!

**Comment by oxalorg** [comment]
The ideas presented here are definitely beneficial, but it has been some time since we last examined it.

I don't think we have time as of now to pursue this further, but if someone feels like they want to tackle this, a good place would be start it of as a plugin.

Regardless small PR's are welcome.
