### ISSUE TITLE
Make output of random seed configurable, off by default

### ISSUE THREAD

**Issue by tonsky** [lambdaisland/kaocha#57]
I suspect it is rarely needed?

**Comment by plexus** [comment]
Hiding it by default defeats its purpose. When a test run fails because of an ordering issue and you didn't print the seed, then there's no way to go back and reproduce the failure.

What we can do is only print the seed when a test run fails. That would mean it gets printed at the end, which is also more in line with what other test tools do. If people don't even want that then they should disable randomization.
